### ISSUE TITLE
Jenkins-Github integration. Deploy first "alfa" environment on own servers

### ISSUE THREAD

**Issue by rsmolyazhenko** [squid-cache/squid#22]

**Comment by rsmolyazhenko** [comment]
@rousskov I don't have permissions to Assign this issue to me and edit labels. Can you help me with it?

**Comment by rousskov** [comment]
> moved from In Progress to TODO at https://github.com/orgs/squid-cache/projects/1

If you have started working on the item and plan to continue working on it in the foreseeable future, please do not move it back to the  TODO column just because you need to pause for a little bit. 

* The TODO column is meant for things you have not started working on.
* The Done column is for completed work.
* The "In Progress" column is pretty much for everything else.

We can add more columns like Stuck, Needs Review, etc. but let's use this simple 3-column setup until we need something more complex.

**Comment by rousskov** [comment]
> I don't have permissions to Assign this issue to me and edit labels. Can you help me with it?

I can partially help: I have assigned the issue to you so, I hope, you would be able to edit its metadata such as labels. Please let me know if you still cannot.

I do not see a way to allow you to assign issues to yourself without giving you Write access to the repository (which I would rather not to because you do not need it and may accidentally screw things up if you have that access). This seems to be a Github limitation -- issue access rights are tied to repository access rights. I do not think this is a big deal -- we can live with only a few folks assigning issues because it is a rare event.

**Comment by rousskov** [comment]
> tommorow I will fix last integration problems and we will run some tests with commits, branches and pull requests

Sounds good. Glad you started making progress.

**Comment by eduard-bagdasaryan** [comment]
I began working on 'Jenkins-Github integration' issue. I started with creation a simple installation in my own environment and performing some trivial tests to get acquainted with these tools.

**Comment by rousskov** [comment]
Closing this issue mid-flight because it currently contains almost no useful information, and the Project decided to close Github Issues.

This premature issue closure has no affect on the ongoing work to restore Jenkins-driven CI tests in general or this first "alpha" environment step in particular.
